p8105_hw1_rw3031
================
Polly Wu (rw3031)
2024-09-12

# Problem 1

I installed the package palmerpenguins.

## Describe the penguin dataset

``` r
data("penguins", package = "palmerpenguins")
str(penguins)
```

    ## tibble [344 × 8] (S3: tbl_df/tbl/data.frame)
    ##  $ species          : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ island           : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
    ##  $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
    ##  $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
    ##  $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...
    ##  $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
    ##  $ sex              : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
    ##  $ year             : int [1:344] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

There are 8 variables in the penguin dataset. Species is a factor
variable with 3 levels, island is a factor variable with 3 levels,
bill_length_mm is a numeric variable, flipper_length_mm is a numeric
variable, body_mass_g is a numeric variable, sex is a factor with 2
levels, and year is a numeric variable. The penguins data set contains 8
columns and 344 rows. The mean flipper length is 200.9152.

## Scatterplot

``` r
library(ggplot2)
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_rw3031_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

# Problem 2

## Create the data frame

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ lubridate 1.9.3     ✔ tibble    3.2.1
    ## ✔ purrr     1.0.2     ✔ tidyr     1.3.1
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
df_p2 = tibble(
  random_value = rnorm(n=10, mean=1),
  value_positive = random_value>0,
  char = c("a","b","c","d","e","f","g","h","i","j"),
  factor = c("level1", "level2","level3", "level1", "level2", "level3","level1", "level2", "level3", "level1")
  )
```

## Obtain the mean of the variables

``` r
mean(pull(df_p2,random_value))
```

    ## [1] 1.243707

``` r
mean(pull(df_p2,value_positive))
```

    ## [1] 0.9

``` r
mean(pull(df_p2,char))
```

    ## Warning in mean.default(pull(df_p2, char)): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

``` r
mean(pull(df_p2,factor))
```

    ## Warning in mean.default(pull(df_p2, factor)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

We can only obtain the mean for logical and numeric variables. For
character and factor variables, we cannot obtain their mean.

## Convert to numeric

``` r
as.numeric(pull(df_p2,value_positive))
as.numeric(pull(df_p2,char))
as.numeric(pull(df_p2,factor))
```

The transformation of the character and factor variables return NA.
